name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

     # Step 3: Compile dependencies
      - name: Download dependencies
        run: |
          mkdir -p lib
          wget -q https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-9.0.0.jar -O lib/mysql-connector-j-9.0.0.jar
      
      # Step 4: Compile Java files
      - name: Compile Java files
        run: |
          mkdir -p out
          javac -cp "lib/*:." -d out $(find . -name "*.java")

      # Step 5: Run Unit Tests
      - name: Run unit tests
        run: |
          java -cp "lib/*:out:." org.junit.runner.JUnitCore LoginAppTest
